apiVersion: v1
kind: Secret
metadata:
  name: {{ "{{ .Release.Name }}" }}-secrets
  labels:
    app: ecopackai
type: Opaque
data:
  DATABASE_URL: {{ "{{ .Values.secrets.databaseUrl | b64enc | quote }}" }}
  REDIS_URL: {{ "{{ .Values.secrets.redisUrl | b64enc | quote }}" }}
  JWT_SECRET_KEY: {{ "{{ .Values.secrets.jwtSecretKey | b64enc | quote }}" }}
